version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py loaddata items/fixtures/items.json && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - stripe-cli

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: "listen --api-key ${STRIPE_SECRET_KEY} --device-name ${STRIPE_DEVICE_NAME} --forward-to http://web:8000/webhook/stripe/"
    env_file:
        - .env